Fix merge conflicts (#41)
* Merge develop to master (#20)

* Ignore age check for staff (#17)

* Update auth.py

* Update README.md

* SMS Notifications (#18)

* Feature/sms notifications with delay (#19)

* SMS Notifications

* Rename field verbose name & add translation

Fields modified:
    * sms_sms_reminder
    * sms_reminder_delay

* Increase the max value limit for reminder

* Migration

* address -> street_address

* use address_postal_full instead street_address

* AssertionError fix

AssertionError: Re-adding the same key breaks proper expiration

* Bump Django to 2.2.9 (#22)

* Merge branch 'master' of https://github.com/ezkat/respa into fix-master-conflicts

Co-authored-by: Jussi Heikkilä <jussi.heikkila@haltu.fi>