Merge develop to master (#42)
* Use distinct on unit queryset

* Change validation of management view

* Fix API document version numbering

* Change filter_reserver_info search behaviour

* Change login view texts

* Add missing translations for Respa admin unit views

* Respa admin: translation for unnamed new time period

* Enforce language in respa admin unit view tests

* Pseudonymize user data

* Add tests for pseudonymizing user data

* Change to correct term anonymization, remove unnecessary if clause

* Update OpenAPI spec (#647)

* Update OpenAPI spec

Update OpenAPI specification to include test server url

* fix url typo

* RESPA-177 | Enable Unit Admins and Unit Managers to bypass payment (#649)

* Add permissions for unit manager

* Make changes according to review

* Create can_bypass_payments permission

* Minor changes to payment bypass and add tests

* Add documentation for can_bypass_payment

* Add translations

* Fill in tests for manager level as well

* Change user permissions test to actually test ignoring payment

* Add custom_label property to generic select component

* Change translation

* Changes according to code review

* Changed double quotes to single

* Minor refactor to minimize redundancy in select element template

* Anonymize uuid

* Ignore age check for staff (#17)

* Update auth.py

* I hate mondays

* Database query optimizations for resource and reservation API endpoints

* Changed function level imports to module level in auth helper

* Add is_manager to permissions object

* Allow admins to bypass min_period

* Created missing migrations for changes in accessibility models

* Add unit viewer role which grants right to modify and see certain fields in reservations

* Remove hvara import

* Upgrade Pillo and Django

* Added translations for changes in unit viewer role

* Remove extra border width definition from text area (#656)

* Added instructions to Open API documentation for usage of multiple extra data fields with include parameter (#662)

* Update README.md

* Update requests and sentry-sdk

* Upgrade JS dependencies

* Upgrade helusers and make necessary adjustments

* Update django-helusers to 0.5.5

* Change staticfiles to static in HTML templates

* Create pytest filters to avoid non-relevant warnings

* Change order of installed apps (#665)

* Set anonymized reservations state to cancelled

* Add .env.example and update README.md

* SMS Notifications (#18)

* Added token and session authentications for single resource viewset

* Refactor comment choices

* Change naming

* Feature/sms notifications with delay (#19)

* SMS Notifications

* Rename field verbose name & add translation

Fields modified:
    * sms_sms_reminder
    * sms_reminder_delay

* Increase the max value limit for reminder

* Migration

* address -> street_address

* use address_postal_full instead street_address

* Add project versioning to browsable API interface

* AssertionError fix

AssertionError: Re-adding the same key breaks proper expiration

* Move custom renderer under repsa folder

* Kulkunen SiPass driver changes (#672)

* Kulkunen SiPass driver changes due to changes in SiPass API

* Override DRF's TokenAdmin

* Various permission fixes and improvements (#671)

* Fix admin bypassing time restrictions

* Add extra checks to removing user permissions in JS

* Change order-by-link class hover background-color

* Initial

* Bump Django to 2.2.9 (#21)

* Bump Django to 2.2.9

* Bump Django to 2.2.9

* Add&Update requirements

* Added can_comment_reservations and can_view_reservation_user permissions for Unit Managers

* Some fixes and additions to permissions improvements (#679)

* Fixed bug where anonymizing users didn't anonymize data in related SocialAccount and EmailAddress models causing errors (#680)

* Allow customizing respa admin theme

* Update Python dependencies to secure versions

* Upgrade vulnerable dependencies and switch to using npm

* Add Theme customization block in README

* Update packages (#23)

* Update requirements.txt

* Bump django to 2.2.10

django-allauth to 0.41.0
pillow to 7.0.0

* Added payment terms field to Resource model and API. Also added the field to Respa Admin and tests.

* Added translations

* Check user from kwargs first

* Bump up version number

* Add Matomo analytics snippet to base template

* Fix merge conflicts with helsinki's respa (#1)

* Use distinct on unit queryset

* Change validation of management view

* Fix API document version numbering

* Change filter_reserver_info search behaviour

* Change login view texts

* Add missing translations for Respa admin unit views

* Respa admin: translation for unnamed new time period

* Enforce language in respa admin unit view tests

* Pseudonymize user data

* Add tests for pseudonymizing user data

* Change to correct term anonymization, remove unnecessary if clause

* Update OpenAPI spec (#647)

* Update OpenAPI spec

Update OpenAPI specification to include test server url

* fix url typo

* RESPA-177 | Enable Unit Admins and Unit Managers to bypass payment (#649)

* Add permissions for unit manager

* Make changes according to review

* Create can_bypass_payments permission

* Minor changes to payment bypass and add tests

* Add documentation for can_bypass_payment

* Add translations

* Fill in tests for manager level as well

* Change user permissions test to actually test ignoring payment

* Add custom_label property to generic select component

* Change translation

* Changes according to code review

* Changed double quotes to single

* Minor refactor to minimize redundancy in select element template

* Anonymize uuid

* Database query optimizations for resource and reservation API endpoints

* Changed function level imports to module level in auth helper

* Add is_manager to permissions object

* Allow admins to bypass min_period

* Created missing migrations for changes in accessibility models

* Add unit viewer role which grants right to modify and see certain fields in reservations

* Remove hvara import

* Upgrade Pillo and Django

* Added translations for changes in unit viewer role

* Remove extra border width definition from text area (#656)

* Added instructions to Open API documentation for usage of multiple extra data fields with include parameter (#662)

* Update requests and sentry-sdk

* Upgrade JS dependencies

* Upgrade helusers and make necessary adjustments

* Update django-helusers to 0.5.5

* Change staticfiles to static in HTML templates

* Create pytest filters to avoid non-relevant warnings

* Change order of installed apps (#665)

* Set anonymized reservations state to cancelled

* Add .env.example and update README.md

* Added token and session authentications for single resource viewset

* Refactor comment choices

* Change naming

* Add project versioning to browsable API interface

* Move custom renderer under repsa folder

* Kulkunen SiPass driver changes (#672)

* Kulkunen SiPass driver changes due to changes in SiPass API

* Override DRF's TokenAdmin

* Various permission fixes and improvements (#671)

* Fix admin bypassing time restrictions

* Add extra checks to removing user permissions in JS

* Change order-by-link class hover background-color

* Added can_comment_reservations and can_view_reservation_user permissions for Unit Managers

* Some fixes and additions to permissions improvements (#679)

* Fixed bug where anonymizing users didn't anonymize data in related SocialAccount and EmailAddress models causing errors (#680)

* Allow customizing respa admin theme

* Update Python dependencies to secure versions

* Upgrade vulnerable dependencies and switch to using npm

* Add Theme customization block in README

* Check user from kwargs first

* Bump up version number

* Remove tkusers, use inherit instead

* Push files that git missed because of WSL permission conflicts

* Re-add code that randomly vanished

* Merge remote-tracking branch 'helsinki/develop' into FIX/level-to-helsinki

* Remove duplicate translations

* Remove duplicate function

* Relative import

* Remove unnecessary import

* Fix tests

* OAuth2Adapter -> HelsinkiOAuth2Adapter

* Fix import

Co-authored-by: otiala <44601448+otiala@users.noreply.github.com>
Co-authored-by: Petteri Laine <petteri.laine@iki.fi>
Co-authored-by: tommimanbytes <56429082+tommimanbytes@users.noreply.github.com>
Co-authored-by: Juha Suvanto <38026367+juhasuv@users.noreply.github.com>

* timedelta -> datetime.timedelta (#2)

* Squash some migrations created from editing users model (#3)

* Fix/merge duplicates (#4)

* Remove duplicates

* Squash migrations

* Fix signals not firing on cancelled reservations

* Optimize

* Bump PyYAML to 5.3 (#25)

* Requirements, remove exchangelib logging

* Remove duplicate translations

* Optimize

* Update .gitignore

* Added missing resource migrations

* Fix wrong timezone sent to outlook when appointment was made through api

(And bit more optimization)

* Bump django to 2.2.11 (#28)

* Machine to machine authentication (#29)

* Added M2M auth endpoint

* Daemon thread

* Who put that in there?

* Taggit search fields (#30)

* Add django-taggit

* Add tag field to respa_admin

* Update .travis.yml

* Update .travis.yml

* Make respa_exchange toggleable

* Revert .travis config

* Merge migrations

* Extend helusers SocialAccountAdapter

* Extend helusers SocialAccountAdapter, set assumed uuid

* Merge branch 'develop' into feature/outlook-integration

* Use provided email address as primary

* Merge branch 'develop' into feature/outlook-integration

* Remove duplicate columns from migration files

* Return resource keywords via api

* Feature/reservation home municipality (#31)

* Added home municipality field for reservations

* Added translations to home municipalities

* Added home municipalities to ra resource form

* Added fi translations

* Changed home municipality model naming and reservation home municipality to be object with translations rather than simple char field

* Changed how home municipalites are shown in admin and fixes to home municipality api logic

* Changed home municipality to not be always required via api

* Added home municipality field and set str tests

* Fixed reservation home municipality not handling dicts correctly via api

* Added sv translations for home municipality

* Added migrations for home municipality data

* Feature/phonenumber filter (#32)

* Filter reservations with reserver_phone_number

* change phonenumber default to str

* Feature/reservations without authentication (#33)

* Added unauthenticated option to resource auths

* Check for AnonymousUser

Co-authored-by: SanttuA <santtualatalo@gmail.com>

* Added validation checks for resource form to handle unauthenticated resource auth type (#34)

* Feature/var156 abloy integration (#35)

Added Abloy integration for kulkunen access code system. Abloy integration works mostly in the same way as sipass and requires an outside cronjob to run sync_kulkunen.

* Changed sms reminders to only allow certain notification types (#37)

* Fix search filter (#38)

* Merge upstream to develop (#39)

* Merge upstream/develop

* Bump django-parler

* Revert test changes

* Fix merge conflicts (#41)

* Merge develop to master (#20)

* Ignore age check for staff (#17)

* Update README.md

* SMS Notifications (#18)

* Feature/sms notifications with delay (#19)

* SMS Notifications

* Rename field verbose name & add translation

Fields modified:
    * sms_sms_reminder
    * sms_reminder_delay

* Increase the max value limit for reminder

* Bump django to 2.2.14 (#36)

& update insecure packages

Co-authored-by: Jussi Heikkilä <jussi.heikkila@haltu.fi>
Co-authored-by: Oskari Tiala <oskari.tiala@haltu.fi>
Co-authored-by: Petteri Laine <petteri.l.laine@hel.fi>
Co-authored-by: Jussi Heikkilä <jussi.heikkila@haltu.fi>
Co-authored-by: otiala <44601448+otiala@users.noreply.github.com>
Co-authored-by: Tommi Mantila <tommi@manbytes.fi>
Co-authored-by: tommimanbytes <56429082+tommimanbytes@users.noreply.github.com>
Co-authored-by: Juha Suvanto <38026367+juhasuv@users.noreply.github.com>
Co-authored-by: Petteri Laine <petteri.laine@iki.fi>
Co-authored-by: aceViilee <51813121+aceViilee@users.noreply.github.com>
Co-authored-by: SanttuA <santtualatalo@gmail.com>